<a href="https://colab.research.google.com/github/asyahdin/Introduction-to-Python/blob/main/DecisionTree_SVM_Drug_2407024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
!wget -O drug200.csv https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv

--2024-07-25 03:10:32--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 198.23.119.245
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|198.23.119.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5827 (5.7K) [text/csv]
Saving to: ‘drug200.csv’

drug200.csv         100%[===================>]   5.69K  --.-KB/s    in 0s      

2024-07-25 03:10:33 (1.87 GB/s) - ‘drug200.csv’ saved [5827/5827]



In [15]:
import pandas as pd

df = pd.read_csv("drug200.csv")
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [17]:
df['Drug'].value_counts()

Drug
drugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [18]:
#in code categorical

import numpy as np
x =df.iloc[:,:-1].values
x[:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [19]:
y = df['Drug']

#to convert categorical to numeric

In [20]:
#to convert categorical to numeric

from sklearn.preprocessing import LabelEncoder

label_sex = LabelEncoder()
x[:, 1] = label_sex.fit_transform(x[:, 1])

label_BP = LabelEncoder()
x[:, 2] = label_BP.fit_transform(x[:, 2])

label_chole = LabelEncoder()
x[:, 3] = label_chole.fit_transform(x[:, 3])

x[:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

**Train and test**

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1)

x_train.shape

(150, 5)

**Fit, predict, evaluate**

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import jaccard_score

DS = DecisionTreeClassifier()

#training
DS.fit(x_train, y_train)

#predicition
y_hat = DS.predict(x_test)

#evaluation
print('The accuracy score is: ', accuracy_score(y_test, y_hat))
print('')
print ('The CM is: ', confusion_matrix(y_test, y_hat))
print('')
print ('The jaccard score is: ', jaccard_score(y_test, y_hat, average='micro')) #more than 2 can calc results


The accuracy score is:  1.0

The CM is:  [[ 4  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 21]]

The jaccard score is:  1.0


DATA MODELING - SVM

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

x_train.shape

(160, 5)

In [24]:
#modeling
from sklearn.svm import SVC #this is for RBF
from sklearn.metrics import accuracy_score

SVM_drug = SVC()

#training
SVM_drug.fit(x_train, y_train)

#prediction
y_hat= SVM_drug.predict(x_test)

#evaluation
print('The accuracy based on RBD kernal is: ', (accuracy_score(y_test, y_hat))*100)

The accuracy based on RBD kernal is:  72.5


In [25]:
SVM_drug = SVC(kernel='linear') # so if not change the parameters the default kernel is rbf!! #The result must have higher than rbf #processing time is faster than rbf

#training
SVM_drug.fit(x_train, y_train)

#prediction
y_hat= SVM_drug.predict(x_test)

#evaluation
print('The accuracy based on RBD kernal is: ', (accuracy_score(y_test, y_hat))*100)

The accuracy based on RBD kernal is:  100.0


In [26]:
SVM_drug = SVC(kernel='poly') #using parameter poly #The result is same with rbf

#training
SVM_drug.fit(x_train, y_train)

#prediction
y_hat= SVM_drug.predict(x_test)

#evaluation
print('The accuracy based on RBD kernal is: ', (accuracy_score(y_test, y_hat))*100)

The accuracy based on RBD kernal is:  75.0


In [27]:
SVM_drug = SVC(kernel='sigmoid') #using parameter poly #The result is lowest among other kernel

#training
SVM_drug.fit(x_train, y_train)

#prediction
y_hat= SVM_drug.predict(x_test)

#evaluation
print('The accuracy based on RBD kernal is: ', (accuracy_score(y_test, y_hat))*100)

The accuracy based on RBD kernal is:  35.0
